SYSTEM_NAME="alephone"
SYSTEM_FULLNAME="Aleph One"
SYSTEM_MANUFACTURER="Bungie"
SYSTEM_RELEASE="1994"
SYSTEM_HARDWARE="game engine"
SYSTEM_PATH="/storage/roms/alephone"
SYSTEM_EXTENSION=".alephone"
SYSTEM_PLATFORM="pc"
SYSTEM_THEME="alephone"
SYSTEM_WIKI_PATH="alephone"